---
apiVersion: v1
kind: Namespace
metadata:
  name: do-floating-ip-controller-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: do-floating-ip-controller-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-actions-do-floating-ip-controller
  namespace: do-floating-ip-controller-system
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - "*"
  - apiGroups:
      - "scheduling.k8s.io"
    resources:
      - priorityclasses
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-do-floating-ip-controller
  namespace: do-floating-ip-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-actions-do-floating-ip-controller
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: do-floating-ip-controller-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-actions
  namespace: do-floating-ip-controller-system
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - "*"
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - "*"
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - serviceaccounts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions
  namespace: do-floating-ip-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-actions
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: do-floating-ip-controller-system
