# permissions for end users to edit floatingipbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floatingipbinding-editor-role
rules:
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings/status
  verbs:
  - get
