# permissions for end users to view floatingipbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floatingipbinding-viewer-role
rules:
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings/status
  verbs:
  - get
