---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings/finalizers
  verbs:
  - update
- apiGroups:
  - digitalocean.smirlwebs.com
  resources:
  - floatingipbindings/status
  verbs:
  - get
  - patch
  - update
