apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: do-floating-ip-controller
                key: DO_TOKEN
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      priorityClassName: do-floating-ip-controller-priority-class
