name: Release

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/smirl/digitalocean-floating-ip-controller

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    needs:
      - build
    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.19.4'

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.0.5"

      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SECRET }}

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.10'

      - name: Deploy
        run: IMG=ghcr.io/smirl/digitalocean-floating-ip-controller:$GIT_TAG_NAME make deploy
